# The sessions to analyze
#sessions : ['i140703-001','l101210-001']
sessions : ['i140703-001','l101210-001']
# The 5 epochs to analyze
epochs : ['start', 'cue1', 'earlydelay', 'latedelay', 'movement', 'hold']
# The 4 trial types to analyze
trialtypes : ['PGHF', 'PGLF' ,'SGHF', 'SGLF' ]
# Absolute (independent of the number of spikes) minimum number of occurrences of a pattern
abs_min_occ : 10
# Minimum number of spikes
abs_min_spikes : 2.
# The binsize to use to run the spade analysis in seconds
binsize : 0.005
# Percentile of Poisson pattern count to set minimum occ (int between 0 and 100)
percentile_poiss : 95
# the percentile of the rate distribution to use to compute min occ (int between 0 and 100)
percentile_rates : 90
# Spectrum to use
spectrum : '3d#'
# sliding window length
winlen : 12
# Dithering to use to generate surrogates in seconds
dither : 0.025
# Number of surrogates to generate
n_surr : 5000
# Significance level
alpha : 0.05
# Surrogate method to use
surr_method : 'trial_shifting'
# Multitesting statistical correction
correction : 'fdr_bh'
# PSR parameters
psr_param : [2, 2, 2]
# Unit in which every time of the analysis is expressed
unit : 's'
# Data being generated
processes : ['ppd', 'gamma']
# Firing rate threshold to exclude neurons in Hz
firing_rate_threshold : 70
# Seed for the data generation
seed : 0
# SNR threshold
SNR_thresh : 2.5
# size for removal of synchrofacts from data
synchsize : 2
